# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Guardrails < Formula
  desc ""
  homepage "https://www.guardrails.io/"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/guardrailsio/guardrails-cli/releases/download/v0.1.0/guardrails_v0.1.0_darwin_arm64.tar.gz"
      sha256 "5af8debdd6caa000ddc3cfb7dbf92574e80fe2fe62d0e13fa211a4be6f838cbe"

      def install
        bin.install "guardrails-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/guardrailsio/guardrails-cli/releases/download/v0.1.0/guardrails_v0.1.0_darwin_x86_64.tar.gz"
      sha256 "d5e06c390b9212da800091cc29f06b552a6347ec35917284d34273f6a0ecc14b"

      def install
        bin.install "guardrails-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guardrailsio/guardrails-cli/releases/download/v0.1.0/guardrails_v0.1.0_linux_arm64.tar.gz"
      sha256 "52c647d68da5f489dd4e18e883fae99025c482e5877d11e99f73d5a0d262d2f6"

      def install
        bin.install "guardrails-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/guardrailsio/guardrails-cli/releases/download/v0.1.0/guardrails_v0.1.0_linux_x86_64.tar.gz"
      sha256 "d633e359dcca41c66706290ddecb08c8c1d9f3749b1d977217ca22240a655fce"

      def install
        bin.install "guardrails-cli"
      end
    end
  end
end
