# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Guardrails < Formula
  desc ""
  homepage "https://www.guardrails.io/"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/guardrailsio/guardrails-cli/releases/download/v0.1.0/guardrails_v0.1.0_darwin_arm64.tar.gz"
      sha256 "0d87a3acea33e85696915f287111e4a5688560e910bdd2455b5237a6db275298"

      def install
        bin.install "guardrails-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/guardrailsio/guardrails-cli/releases/download/v0.1.0/guardrails_v0.1.0_darwin_x86_64.tar.gz"
      sha256 "bb51fd4d87d11ec173117c859d65c896d7649e6003f1d96effeb50e8ec98789b"

      def install
        bin.install "guardrails-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/guardrailsio/guardrails-cli/releases/download/v0.1.0/guardrails_v0.1.0_linux_x86_64.tar.gz"
      sha256 "dc5eba2ea4b8585da4ddd8a4380554f41bc4824c7487105491b850dfe7c2cf39"

      def install
        bin.install "guardrails-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guardrailsio/guardrails-cli/releases/download/v0.1.0/guardrails_v0.1.0_linux_arm64.tar.gz"
      sha256 "85089c9e07904de8bb91780b821eb175204999775e7f55014ef114b79a7f2d1c"

      def install
        bin.install "guardrails-cli"
      end
    end
  end
end
