# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Guardrails < Formula
  desc ""
  homepage "https://www.guardrails.io/"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/guardrailsio/guardrails-cli/releases/download/v0.1.0/guardrails_v0.1.0_darwin_x86_64.tar.gz"
      sha256 "eb79add22410eea10af72fad7565e29596cd72ec6b9a5ea23faf352bf773b3e7"

      def install
        bin.install "guardrails-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/guardrailsio/guardrails-cli/releases/download/v0.1.0/guardrails_v0.1.0_darwin_arm64.tar.gz"
      sha256 "886cceeab8da4796b0b8f737150b8b690b7d1b1c04a52c9435b58cd80be063a0"

      def install
        bin.install "guardrails-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/guardrailsio/guardrails-cli/releases/download/v0.1.0/guardrails_v0.1.0_linux_x86_64.tar.gz"
      sha256 "a5fa6230654264ee5e90075475564bc1a7ff353bb84d2165d69f1597902a2a73"

      def install
        bin.install "guardrails-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guardrailsio/guardrails-cli/releases/download/v0.1.0/guardrails_v0.1.0_linux_arm64.tar.gz"
      sha256 "205e74739d372f6b336c8622a8d758ea0ea3e5c037b52d558483f6f60caee9f0"

      def install
        bin.install "guardrails-cli"
      end
    end
  end
end
